HaOai_ChatBot/HaOai_ChatBot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('account/', include('account.urls')),
    path('workspace/', include('workspace.urls')),
    path('document/', include('document.urls')),
    path('chatbot/', include('chatbot.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HaOai_ChatBot/account/urls.py
from django.urls import reverse_lazy
from django.urls import path
from . import views
from . import api_views
from django.contrib.auth import views as auth_views

app_name = "account"
urlpatterns = [
    path('signin/', views.signin_view, name='signin_view'),
    path('sign-out/', views.sign_out_view, name='sign_out_view'),
    path('signup/', views.sign_up_view, name='signup_view'),
    path('verify-mail/', views.verify_mail_view, name='verify_mail_view'),
    path('change-password/', views.change_password_view, name='change_password_view'),
    path('my-profile/', views.my_profile_view, name='my_profile_view'),
    path('user-setting/', views.user_settings_view, name='user_settings_view'),

    # Reset password
    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name='account/jetpro/sign-in/password-reset.html',
        success_url=reverse_lazy('account:password_reset_done')
    ), name='reset_password_view'),

    path('reset-password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/jetpro/sign-in/password-reset-done.html',
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/jetpro/sign-in/new-password.html',
        success_url=reverse_lazy('account:password_reset_complete')
    ), name='password_reset_confirm'),

    path('reset-password-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/jetpro/sign-in/password-reset-complete.html',
    ), name='password_reset_complete'),

    ### Api View ###
    path('api/v1/signin/', api_views.signin_api_view, name='signin_api_view'),
    path('api/v1/signup/', api_views.signup_api_view, name='signup_api_view'),
    path('api/v1/verify-otp/', api_views.verify_otp_api, name='verify_otp_api'),
    path('api/v1/change-password/', api_views.change_password_api, name='change_password_api'),
    path('api/v1/update-profile/', api_views.update_profile_api, name='update_profile_api'),
    path('api/v1/change-email/', api_views.change_email_api, name='change_email_api'),
    path('api/v1/verify-email/', api_views.verify_email_api, name='verify_email_api'),
    path('api/v1/deactivate-user/', api_views.deactivate_user_api, name='deactivate_user_api'),
]

HaOai_ChatBot/chatbot/urls.py
from django.urls import path
from . import views, api_views

app_name = 'chatbot'
urlpatterns = [
    path('', views.chat_view, name='chat_view'),

    ### API VIEW ###
    path('api/v1/qa_chatbot/', api_views.qa_chatbot_api, name='qa_chatbot_api'),
]

HaOai_ChatBot/portal/urls.py
from django.urls import path
from . import views

app_name = 'portal'
urlpatterns = [
    path('', views.index_view, name='index_view')
]

HaOai_ChatBot/workspace/urls.py
from django.urls import path
from . import views

app_name = "workspace"
urlpatterns = [
    path("", views.workspace_view, name='workspace_view'),
]

HaOai_ChatBot/portal/views.py
from django.shortcuts import render

def index_view(request):
    return render(request, 'portal/index.html', {})

HaOai_ChatBot/portal/templates/portal/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<!--begin::Head-->
<head>
    <base href="">
    <title>HaOai</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta charset="utf-8"/>
    <meta property="og:locale" content="en_US"/>
    <meta property="og:type" content="article"/>
    <link rel="shortcut icon" href="{% static 'portal/assets/media/logos/logo_haui_v1.png' %}" />
    <!--begin::Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700"/>
    <!--end::Fonts-->
    <!--begin::Global Stylesheets Bundle(used by all pages)-->
    <link href="{% static 'portal/assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'portal/assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css"/>
    <!--end::Global Stylesheets Bundle-->
</head>
<!--end::Head-->
<!--begin::Body-->
<body id="kt_body" style="background: linear-gradient(to bottom right, #FFD700, #B22222);" data-bs-spy="scroll"
      data-bs-target="#kt_landing_menu" data-bs-offset="200" class="position-relative">
<!--begin::Main-->
<div class="d-flex flex-column flex-root">
    <!--begin::Header Section-->
    <div class="mb-0" id="home">
        <!--begin::Wrapper-->
        <div class="bgi-no-repeat bgi-size-contain bgi-position-x-center bgi-position-y-bottom landing-dark-bg"
             style="background-image: url({% static 'portal/assets/media/svg/illustrations/landing.svg)' %}">

            <!--begin::Header-->
            <div class="landing-header" data-kt-sticky="true" data-kt-sticky-name="landing-header"
                 data-kt-sticky-offset="{default: '200px', lg: '300px'}">
                <!--begin::Container-->
                <div class="container">
                    <!--begin::Wrapper-->
                    <div class="d-flex align-items-center justify-content-between">
                        <!--begin::Logo-->
                        <div class="d-flex align-items-center flex-equal">
                            <!--begin::Mobile menu toggle-->
                            <button class="btn btn-icon btn-active-color-primary me-3 d-flex d-lg-none"
                                    id="kt_landing_menu_toggle">
                                <!--begin::Svg Icon | path: icons/duotune/abstract/abs015.svg-->
                                <span class="svg-icon svg-icon-2hx">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                 viewBox="0 0 24 24" fill="none">
												<path d="M21 7H3C2.4 7 2 6.6 2 6V4C2 3.4 2.4 3 3 3H21C21.6 3 22 3.4 22 4V6C22 6.6 21.6 7 21 7Z"
                                                      fill="black"/>
												<path opacity="0.3"
                                                      d="M21 14H3C2.4 14 2 13.6 2 13V11C2 10.4 2.4 10 3 10H21C21.6 10 22 10.4 22 11V13C22 13.6 21.6 14 21 14ZM22 20V18C22 17.4 21.6 17 21 17H3C2.4 17 2 17.4 2 18V20C2 20.6 2.4 21 3 21H21C21.6 21 22 20.6 22 20Z"
                                                      fill="black"/>
											</svg>
										</span>
                                <!--end::Svg Icon-->
                            </button>
                            <!--end::Mobile menu toggle-->
                            <!--begin::Logo image-->
                            <a href="{% url 'portal:index_view' %}">
                                <img alt="Logo" src="{% static 'portal/assets/media/logos/logo_haui_final.png' %}"
                                     class="logo-default h-25px h-lg-30px"/>
                                <img alt="Logo" src="{% static 'portal/assets/media/logos/logo_haui_final.png' %}"
                                     class="logo-sticky h-25px h-lg-30px"/>
                            </a>
                            <!--end::Logo image-->
                        </div>
                        <!--end::Logo-->

                        <!--begin::Toolbar-->

<!--                        <div class="flex-equal text-end ms-1">-->
<!--                            {% if request.user.is_authenticated %}-->
<!--                                <a href="{% url 'workspace:workspace_view' %}" class="btn btn-danger">Dashboard</a>-->
<!--                            {% else %}-->
<!--                                <a href="{% url 'account:signin_view' %}" class="btn btn-danger">Signin</a>-->
<!--                            {% endif %}-->
<!--                        </div>-->
                        <!--end::Toolbar-->
                    </div>
                    <!--end::Wrapper-->
                </div>
                <!--end::Container-->
            </div>
            <!--end::Header-->
            <!--begin::Landing hero-->
            <div class="d-flex flex-column flex-center w-100 min-h-350px min-h-lg-500px px-9">
                <!--begin::Heading-->
                <div class="text-center mb-5 mb-lg-10 py-10 py-lg-20">
                    <!--begin::Title-->
                    <h1 class="text-white lh-base fw-bolder fs-2x fs-lg-3x mb-15">Trợ lý ảo thông minh HaOai
                        <br/>giải đáp mọi thắc mắc về
                        <span style="background: linear-gradient(to right, #12CE5D 0%, #FFD80C 100%);-webkit-background-clip: text;-webkit-text-fill-color: transparent;">
								<span id="kt_landing_hero_text">Đại học Công nghiệp Hà Nội</span>
							</span></h1>
                    <!--end::Title-->
                    <!--begin::Action-->
                    <a href="{% url 'chatbot:chat_view' %}" class="btn btn-primary">Hỏi chatbot</a>
                    <!--end::Action-->
                </div>
                <!--end::Heading-->

            </div>
            <!--end::Landing hero-->
        </div>
        <!--end::Wrapper-->
        <!--begin::Curve bottom-->
        <div class="landing-curve landing-dark-color mb-10 mb-lg-20">
            <svg viewBox="15 12 1470 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 11C3.93573 11.3356 7.85984 11.6689 11.7725 12H1488.16C1492.1 11.6689 1496.04 11.3356 1500 11V12H1488.16C913.668 60.3476 586.282 60.6117 11.7725 12H0V11Z"
                      fill="currentColor"></path>
            </svg>
        </div>
        <!--end::Curve bottom-->
    </div>

</div>
<!--end::Main-->
<script>var hostUrl = "assets/";</script>
<!--begin::Javascript-->
<!--begin::Global Javascript Bundle(used by all pages)-->
<script src="{% static 'portal/assets/plugins/global/plugins.bundle.js' %}"></script>
<script src="{% static 'portal/assets/js/scripts.bundle.js' %}"></script>
<!--end::Global Javascript Bundle-->
<!--begin::Page Vendors Javascript(used by this page)-->
<script src="{% static 'portal/assets/plugins/custom/fslightbox/fslightbox.bundle.js' %}"></script>
<script src="{% static 'portal/assets/plugins/custom/typedjs/typedjs.bundle.js' %}"></script>
<!--end::Page Vendors Javascript-->
<!--begin::Page Custom Javascript(used by this page)-->
<script src="{% static 'portal/assets/js/custom/landing.js' %}"></script>
<script src="{% static 'portal/assets/js/custom/pages/company/pricing.js' %}"></script>
<!--end::Page Custom Javascript-->
<!--end::Javascript-->
</body>
<!--end::Body-->
</html>